version: '3.1'
services:
  db:
    image: postgres:14.5-alpine
    container_name: postgres
    ports:
      - 5100:5432
    volumes:
      - psql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres_db_project_for_job
    restart: always
volumes:
  psql:
