version: '3.1'
services:
  db:
    image: postgres:14.5-alpine
    container_name: postgres
    ports:
      - 5080:5432
    volumes:
      - psql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres_db_project_for_job
    restart: always
#  app:
#    image: server
#    container_name: application
#    ports:
#      - 5000:5000
#    environment:
#      POSTGRES_HOST: db
#    restart: always
#    links:
#      - db
volumes:
  psql:
